- name: "Build Image and run container with ansible playbook"
  hosts: localhost
  tasks:
  - name: stop running container
    command: docker stop laravel-container
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm laravel-container
    ignore_errors: yes

  - name: remove used image
    # Make sure to change the image name with your personal dockerhub account and reposiroty   
    command: docker rmi comingsoon-pages
    ignore_errors: yes

  - name: build docker image from dockerfile
    # Make sure to change the image name with your personal dockerhub account and reposiroty 
    command: docker build -t comingsoon-pages .

  - name: tag the docker image
    command: docker tag comingsoon-pages imas10/comingsoon-pages:0.0.01

  - name: push image to dockerhub
    # Make sure to change the image name with your personal dockerhub account and reposiroty 
    command: docker push imas10/comingsoon-pages:0.0.01




